// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6KlU69jVlKrrdhVv5Y2dq1LpH6lNW9aQ',
    appId: '1:456820134220:web:6eb4d20db47c6f86fbbfe9',
    messagingSenderId: '456820134220',
    projectId: 'login-cea10',
    authDomain: 'login-cea10.firebaseapp.com',
    storageBucket: 'login-cea10.firebasestorage.app',
    measurementId: 'G-4TTP1Z69K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqyBeiMmHG-0azYoOJGCDkvJ5Xck2eQQ',
    appId: '1:456820134220:android:688f3bb52c0ad525fbbfe9',
    messagingSenderId: '456820134220',
    projectId: 'login-cea10',
    storageBucket: 'login-cea10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKv_OOT_w4NOFJbEUFiZpGshLkWlW0xk',
    appId: '1:456820134220:ios:910434b1aefb6473fbbfe9',
    messagingSenderId: '456820134220',
    projectId: 'login-cea10',
    storageBucket: 'login-cea10.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLKv_OOT_w4NOFJbEUFiZpGshLkWlW0xk',
    appId: '1:456820134220:ios:910434b1aefb6473fbbfe9',
    messagingSenderId: '456820134220',
    projectId: 'login-cea10',
    storageBucket: 'login-cea10.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6KlU69jVlKrrdhVv5Y2dq1LpH6lNW9aQ',
    appId: '1:456820134220:web:9b8e5c3b2a56ddb8fbbfe9',
    messagingSenderId: '456820134220',
    projectId: 'login-cea10',
    authDomain: 'login-cea10.firebaseapp.com',
    storageBucket: 'login-cea10.firebasestorage.app',
    measurementId: 'G-M41SLBEZ66',
  );

}